#@data/values
#@overlay/match-child-defaults missing_ok=True
---
infrastructure_provider: "aws"
dex:
  image:
    repository: registry.tkg.vmware.run
  config:
    connector: ldap
    ldap:
      host: 10.10.50.12
      bindDN: CN=tanzubind,CN=Users,DC=hollow,DC=local
      bindPW: QAZxsw2
      userSearch:
        baseDN: dc=hollow,dc=local
        filter: "(objectClass=person)"
        username: sAMAccountName
        idAttr: sAMAccountName
        emailAttr: mail
        nameAttr: cn
      groupSearch:
        baseDN: dc=hollow,dc=local
        filter: "(objectClass=group)"
        userAttr: distinguishedName
        groupAttr: member
        nameAttr: cn
    #! Deploy dex first with dummy staticClients. Once gangway is installed in workload cluster, update static clients with gangway information
    #@overlay/replace
    staticClients:
    - id: WORKLOAD_CLUSTER_NAME
      redirectURIs:
      - 'https://WORKLOAD_CLUSTER_IP:30166/callback'
      name: WORKLOAD_CLUSTER_NAME
      secret: CLIENT_SECRET
#! Deploy dex first and update sample-lb with real name once dex service loadbalancer is created, dnsNames is optional.
dns:
  aws:
    DEX_SVC_LB_HOSTNAME: 
    dnsNames: []